import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Volopay Task | Cards App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={inter.style} className="bg-gray-50">
        <Navbar />
        <Toaster />
        {children}
      </body>
    </html>
  );
}
